### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by MaanasVohra** [MaanasVohra/Student-Discussion-Portal-Frontend#1]
This is a student query portal which will be an SPA built in Angular. It will be used to address the queries of students and could be used for other purposes as well. 
The topics for the queries will have subtopics, and for each subtopic there will be a number of questions. Each question could be answered by the students and students can comment on the answers as well.

**Comment by Knee3** [comment]
I'll do it

**Comment by MaanasVohra** [comment]
@Knee3 Assigned to you
